export const TRANSFER_ADD_REQUEST = "TRANSFER_ADD_REQUEST";
export const TRANSFER_ADD_SUCCESS = "TRANSFER_ADD_SUCCESS";
export const TRANSFER_ADD_FAIL = "TRANSFER_ADD_FAIL";

export const USER_UPDATE_TRANSFER_REQUEST = "USER_UPDATE_TRANSFER_REQUEST";
export const USER_UPDATE_TRANSFER_SUCCESS = "USER_UPDATE_TRANSFER_SUCCESS";
export const USER_UPDATE_TRANSFER_FAIL = "USER_UPDATE_TRANSFER_FAIL";
export const USER_UPDATE_TRANSFER_RESET = "USER_UPDATE_TRANSFER_RESET";
