export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";
export const TRANSACTION_CREATE_RESET = "TRANSACTION_CREATE_RESET";

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";

export const TRANSACTION_PAY_REQUEST = "TRANSACTION_PAY_REQUEST";
export const TRANSACTION_PAY_SUCCESS = "TRANSACTION_PAY_SUCCESS";
export const TRANSACTION_PAY_FAIL = "TRANSACTION_PAY_FAIL";
export const TRANSACTION_PAY_RESET = "TRANSACTION_PAY_RESET";

export const TRANSACTION_LIST_MY_REQUEST = "TRANSACTION_LIST_MY_REQUEST";
export const TRANSACTION_LIST_MY_SUCCESS = "TRANSACTION_LIST_MY_SUCCESS";
export const TRANSACTION_LIST_MY_FAIL = "TRANSACTION_LIST_MY_FAIL";
export const TRANSACTION_LIST_MY_RESET = "TRANSACTION_LIST_MY_RESET";
